- name: Generate and Send Report
  hosts: localhost
  gather_facts: true

  tasks:

    - name: Aggregate VM Metrics into collected_metrics fact
      set_fact:
        collected_metrics: "{{ groups['env_dev'] | map('extract', hostvars, 'vm_metrics') | list | flatten }}"


    - name: Debug collected metrics
      debug:
        var: collected_metrics


    - name: Set Timestamp Fact
      set_fact:
        timestamp: "{{ ansible_facts['date_time']['date'] }} {{ ansible_facts['date_time']['hour'] }}:{{ ansible_facts['date_time']['minute'] }}"

    - name: Check SMTP variables
      debug:
        msg:
          - "SMTP server is {{ smtp_server }}"
          - "SMTP port is {{ smtp_port }}"

    - name: Send animated HTML report via email
      community.general.mail:
        host: "{{ smtp_server }}"
        port: "{{ smtp_port }}"
        username: "{{ user_mail }}"
        password: "{{ password }}"
        to: "{{ destination_mail }}"
        subject: "VM Report - {{ timestamp }}"
        subtype: html
        body: "{{ lookup('template', 'templates/report.html.j2') }}"
